// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.0
// source: proto/smartcity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAddress   string                 `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	DepositUsdc   string                 `protobuf:"bytes,3,opt,name=deposit_usdc,json=depositUsdc,proto3" json:"deposit_usdc,omitempty"`
	UserWireAddr  string                 `protobuf:"bytes,4,opt,name=user_wire_addr,json=userWireAddr,proto3" json:"user_wire_addr,omitempty"` // P2P 주소 (libp2p multiaddr)
	HoldSeconds   int64                  `protobuf:"varint,5,opt,name=hold_seconds,json=holdSeconds,proto3" json:"hold_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_proto_smartcity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{0}
}

func (x *StartSessionRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *StartSessionRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *StartSessionRequest) GetDepositUsdc() string {
	if x != nil {
		return x.DepositUsdc
	}
	return ""
}

func (x *StartSessionRequest) GetUserWireAddr() string {
	if x != nil {
		return x.UserWireAddr
	}
	return ""
}

func (x *StartSessionRequest) GetHoldSeconds() int64 {
	if x != nil {
		return x.HoldSeconds
	}
	return 0
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	EscrowId      string                 `protobuf:"bytes,4,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	HoldDeadline  int64                  `protobuf:"varint,5,opt,name=hold_deadline,json=holdDeadline,proto3" json:"hold_deadline,omitempty"`
	StateHash     string                 `protobuf:"bytes,6,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_proto_smartcity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartSessionResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *StartSessionResponse) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

func (x *StartSessionResponse) GetHoldDeadline() int64 {
	if x != nil {
		return x.HoldDeadline
	}
	return 0
}

func (x *StartSessionResponse) GetStateHash() string {
	if x != nil {
		return x.StateHash
	}
	return ""
}

func (x *StartSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EndSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserAddress   string                 `protobuf:"bytes,3,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	UserFinalSig  string                 `protobuf:"bytes,4,opt,name=user_final_sig,json=userFinalSig,proto3" json:"user_final_sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRequest) Reset() {
	*x = EndSessionRequest{}
	mi := &file_proto_smartcity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRequest) ProtoMessage() {}

func (x *EndSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRequest.ProtoReflect.Descriptor instead.
func (*EndSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{2}
}

func (x *EndSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndSessionRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *EndSessionRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *EndSessionRequest) GetUserFinalSig() string {
	if x != nil {
		return x.UserFinalSig
	}
	return ""
}

type EndSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	FareUsdc      string                 `protobuf:"bytes,2,opt,name=fare_usdc,json=fareUsdc,proto3" json:"fare_usdc,omitempty"`
	RefundUsdc    string                 `protobuf:"bytes,3,opt,name=refund_usdc,json=refundUsdc,proto3" json:"refund_usdc,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionResponse) Reset() {
	*x = EndSessionResponse{}
	mi := &file_proto_smartcity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionResponse) ProtoMessage() {}

func (x *EndSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionResponse.ProtoReflect.Descriptor instead.
func (*EndSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{3}
}

func (x *EndSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *EndSessionResponse) GetFareUsdc() string {
	if x != nil {
		return x.FareUsdc
	}
	return ""
}

func (x *EndSessionResponse) GetRefundUsdc() string {
	if x != nil {
		return x.RefundUsdc
	}
	return ""
}

func (x *EndSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UsageDelta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceType     string                 `protobuf:"bytes,1,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	DurationMinutes float64                `protobuf:"fixed64,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	EnergyKwh       float64                `protobuf:"fixed64,3,opt,name=energy_kwh,json=energyKwh,proto3" json:"energy_kwh,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UsageDelta) Reset() {
	*x = UsageDelta{}
	mi := &file_proto_smartcity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageDelta) ProtoMessage() {}

func (x *UsageDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageDelta.ProtoReflect.Descriptor instead.
func (*UsageDelta) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{4}
}

func (x *UsageDelta) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *UsageDelta) GetDurationMinutes() float64 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *UsageDelta) GetEnergyKwh() float64 {
	if x != nil {
		return x.EnergyKwh
	}
	return 0
}

type ProposeUsageUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UsageDelta    *UsageDelta            `protobuf:"bytes,3,opt,name=usage_delta,json=usageDelta,proto3" json:"usage_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeUsageUpdateRequest) Reset() {
	*x = ProposeUsageUpdateRequest{}
	mi := &file_proto_smartcity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeUsageUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeUsageUpdateRequest) ProtoMessage() {}

func (x *ProposeUsageUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeUsageUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProposeUsageUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{5}
}

func (x *ProposeUsageUpdateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProposeUsageUpdateRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ProposeUsageUpdateRequest) GetUsageDelta() *UsageDelta {
	if x != nil {
		return x.UsageDelta
	}
	return nil
}

type ProposeUsageUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	FareUsdc      string                 `protobuf:"bytes,2,opt,name=fare_usdc,json=fareUsdc,proto3" json:"fare_usdc,omitempty"`
	PolicyHash    string                 `protobuf:"bytes,3,opt,name=policy_hash,json=policyHash,proto3" json:"policy_hash,omitempty"`
	NewNonce      int64                  `protobuf:"varint,4,opt,name=new_nonce,json=newNonce,proto3" json:"new_nonce,omitempty"`
	StateHash     string                 `protobuf:"bytes,5,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	BalanceUser   string                 `protobuf:"bytes,6,opt,name=balance_user,json=balanceUser,proto3" json:"balance_user,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeUsageUpdateResponse) Reset() {
	*x = ProposeUsageUpdateResponse{}
	mi := &file_proto_smartcity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeUsageUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeUsageUpdateResponse) ProtoMessage() {}

func (x *ProposeUsageUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeUsageUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProposeUsageUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{6}
}

func (x *ProposeUsageUpdateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ProposeUsageUpdateResponse) GetFareUsdc() string {
	if x != nil {
		return x.FareUsdc
	}
	return ""
}

func (x *ProposeUsageUpdateResponse) GetPolicyHash() string {
	if x != nil {
		return x.PolicyHash
	}
	return ""
}

func (x *ProposeUsageUpdateResponse) GetNewNonce() int64 {
	if x != nil {
		return x.NewNonce
	}
	return 0
}

func (x *ProposeUsageUpdateResponse) GetStateHash() string {
	if x != nil {
		return x.StateHash
	}
	return ""
}

func (x *ProposeUsageUpdateResponse) GetBalanceUser() string {
	if x != nil {
		return x.BalanceUser
	}
	return ""
}

func (x *ProposeUsageUpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetChannelStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelStatusRequest) Reset() {
	*x = GetChannelStatusRequest{}
	mi := &file_proto_smartcity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelStatusRequest) ProtoMessage() {}

func (x *GetChannelStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelStatusRequest.ProtoReflect.Descriptor instead.
func (*GetChannelStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{7}
}

func (x *GetChannelStatusRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ChannelStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Nonce         int64                  `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BalanceUser   string                 `protobuf:"bytes,3,opt,name=balance_user,json=balanceUser,proto3" json:"balance_user,omitempty"`
	BalanceOp     string                 `protobuf:"bytes,4,opt,name=balance_op,json=balanceOp,proto3" json:"balance_op,omitempty"`
	StateHash     string                 `protobuf:"bytes,5,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelStatusResponse) Reset() {
	*x = ChannelStatusResponse{}
	mi := &file_proto_smartcity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStatusResponse) ProtoMessage() {}

func (x *ChannelStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStatusResponse.ProtoReflect.Descriptor instead.
func (*ChannelStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{8}
}

func (x *ChannelStatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ChannelStatusResponse) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *ChannelStatusResponse) GetBalanceUser() string {
	if x != nil {
		return x.BalanceUser
	}
	return ""
}

func (x *ChannelStatusResponse) GetBalanceOp() string {
	if x != nil {
		return x.BalanceOp
	}
	return ""
}

func (x *ChannelStatusResponse) GetStateHash() string {
	if x != nil {
		return x.StateHash
	}
	return ""
}

func (x *ChannelStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InitiateDisputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateDisputeRequest) Reset() {
	*x = InitiateDisputeRequest{}
	mi := &file_proto_smartcity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateDisputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateDisputeRequest) ProtoMessage() {}

func (x *InitiateDisputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateDisputeRequest.ProtoReflect.Descriptor instead.
func (*InitiateDisputeRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{9}
}

func (x *InitiateDisputeRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type InitiateDisputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateDisputeResponse) Reset() {
	*x = InitiateDisputeResponse{}
	mi := &file_proto_smartcity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateDisputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateDisputeResponse) ProtoMessage() {}

func (x *InitiateDisputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateDisputeResponse.ProtoReflect.Descriptor instead.
func (*InitiateDisputeResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{10}
}

func (x *InitiateDisputeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InitiateDisputeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AccumulateCreditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	CreditUsdc    string                 `protobuf:"bytes,2,opt,name=credit_usdc,json=creditUsdc,proto3" json:"credit_usdc,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccumulateCreditRequest) Reset() {
	*x = AccumulateCreditRequest{}
	mi := &file_proto_smartcity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccumulateCreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccumulateCreditRequest) ProtoMessage() {}

func (x *AccumulateCreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccumulateCreditRequest.ProtoReflect.Descriptor instead.
func (*AccumulateCreditRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{11}
}

func (x *AccumulateCreditRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *AccumulateCreditRequest) GetCreditUsdc() string {
	if x != nil {
		return x.CreditUsdc
	}
	return ""
}

func (x *AccumulateCreditRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AccumulateCreditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Total         string                 `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccumulateCreditResponse) Reset() {
	*x = AccumulateCreditResponse{}
	mi := &file_proto_smartcity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccumulateCreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccumulateCreditResponse) ProtoMessage() {}

func (x *AccumulateCreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccumulateCreditResponse.ProtoReflect.Descriptor instead.
func (*AccumulateCreditResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{12}
}

func (x *AccumulateCreditResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AccumulateCreditResponse) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *AccumulateCreditResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PostCompensationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAddress   string                 `protobuf:"bytes,1,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
	AmountUsdc    string                 `protobuf:"bytes,2,opt,name=amount_usdc,json=amountUsdc,proto3" json:"amount_usdc,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCompensationRequest) Reset() {
	*x = PostCompensationRequest{}
	mi := &file_proto_smartcity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCompensationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCompensationRequest) ProtoMessage() {}

func (x *PostCompensationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCompensationRequest.ProtoReflect.Descriptor instead.
func (*PostCompensationRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{13}
}

func (x *PostCompensationRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *PostCompensationRequest) GetAmountUsdc() string {
	if x != nil {
		return x.AmountUsdc
	}
	return ""
}

func (x *PostCompensationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PostCompensationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCompensationResponse) Reset() {
	*x = PostCompensationResponse{}
	mi := &file_proto_smartcity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCompensationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCompensationResponse) ProtoMessage() {}

func (x *PostCompensationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCompensationResponse.ProtoReflect.Descriptor instead.
func (*PostCompensationResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{14}
}

func (x *PostCompensationResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PostCompensationResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *PostCompensationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogRequest) Reset() {
	*x = AuditLogRequest{}
	mi := &file_proto_smartcity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogRequest) ProtoMessage() {}

func (x *AuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogRequest.ProtoReflect.Descriptor instead.
func (*AuditLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{15}
}

func (x *AuditLogRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLogRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type AuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	LogId         string                 `protobuf:"bytes,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogResponse) Reset() {
	*x = AuditLogResponse{}
	mi := &file_proto_smartcity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogResponse) ProtoMessage() {}

func (x *AuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogResponse.ProtoReflect.Descriptor instead.
func (*AuditLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{16}
}

func (x *AuditLogResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuditLogResponse) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_smartcity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{17}
}

func (x *StreamEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamEventsRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_smartcity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smartcity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_smartcity_proto_rawDescGZIP(), []int{18}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_smartcity_proto protoreflect.FileDescriptor

const file_proto_smartcity_proto_rawDesc = "" +
	"\n" +
	"\x15proto/smartcity.proto\x12\tsmartcity\"\xc3\x01\n" +
	"\x13StartSessionRequest\x12!\n" +
	"\fuser_address\x18\x01 \x01(\tR\vuserAddress\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12!\n" +
	"\fdeposit_usdc\x18\x03 \x01(\tR\vdepositUsdc\x12$\n" +
	"\x0euser_wire_addr\x18\x04 \x01(\tR\fuserWireAddr\x12!\n" +
	"\fhold_seconds\x18\x05 \x01(\x03R\vholdSeconds\"\xdb\x01\n" +
	"\x14StartSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tescrow_id\x18\x04 \x01(\tR\bescrowId\x12#\n" +
	"\rhold_deadline\x18\x05 \x01(\x03R\fholdDeadline\x12\x1d\n" +
	"\n" +
	"state_hash\x18\x06 \x01(\tR\tstateHash\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\x9a\x01\n" +
	"\x11EndSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12!\n" +
	"\fuser_address\x18\x03 \x01(\tR\vuserAddress\x12$\n" +
	"\x0euser_final_sig\x18\x04 \x01(\tR\fuserFinalSig\"x\n" +
	"\x12EndSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tfare_usdc\x18\x02 \x01(\tR\bfareUsdc\x12\x1f\n" +
	"\vrefund_usdc\x18\x03 \x01(\tR\n" +
	"refundUsdc\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"y\n" +
	"\n" +
	"UsageDelta\x12!\n" +
	"\fservice_type\x18\x01 \x01(\tR\vserviceType\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x01R\x0fdurationMinutes\x12\x1d\n" +
	"\n" +
	"energy_kwh\x18\x03 \x01(\x01R\tenergyKwh\"\x91\x01\n" +
	"\x19ProposeUsageUpdateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x126\n" +
	"\vusage_delta\x18\x03 \x01(\v2\x15.smartcity.UsageDeltaR\n" +
	"usageDelta\"\xdf\x01\n" +
	"\x1aProposeUsageUpdateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\tfare_usdc\x18\x02 \x01(\tR\bfareUsdc\x12\x1f\n" +
	"\vpolicy_hash\x18\x03 \x01(\tR\n" +
	"policyHash\x12\x1b\n" +
	"\tnew_nonce\x18\x04 \x01(\x03R\bnewNonce\x12\x1d\n" +
	"\n" +
	"state_hash\x18\x05 \x01(\tR\tstateHash\x12!\n" +
	"\fbalance_user\x18\x06 \x01(\tR\vbalanceUser\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"8\n" +
	"\x17GetChannelStatusRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\xb4\x01\n" +
	"\x15ChannelStatusResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x03R\x05nonce\x12!\n" +
	"\fbalance_user\x18\x03 \x01(\tR\vbalanceUser\x12\x1d\n" +
	"\n" +
	"balance_op\x18\x04 \x01(\tR\tbalanceOp\x12\x1d\n" +
	"\n" +
	"state_hash\x18\x05 \x01(\tR\tstateHash\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"7\n" +
	"\x16InitiateDisputeRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"?\n" +
	"\x17InitiateDisputeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"q\n" +
	"\x17AccumulateCreditRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1f\n" +
	"\vcredit_usdc\x18\x02 \x01(\tR\n" +
	"creditUsdc\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"V\n" +
	"\x18AccumulateCreditResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05total\x18\x02 \x01(\tR\x05total\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"u\n" +
	"\x17PostCompensationRequest\x12!\n" +
	"\fuser_address\x18\x01 \x01(\tR\vuserAddress\x12\x1f\n" +
	"\vamount_usdc\x18\x02 \x01(\tR\n" +
	"amountUsdc\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"Y\n" +
	"\x18PostCompensationResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"E\n" +
	"\x0fAuditLogRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\"9\n" +
	"\x10AuditLogResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x15\n" +
	"\x06log_id\x18\x02 \x01(\tR\x05logId\"S\n" +
	"\x13StreamEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"S\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\x85\x06\n" +
	"\rSmartCityNode\x12O\n" +
	"\fStartSession\x12\x1e.smartcity.StartSessionRequest\x1a\x1f.smartcity.StartSessionResponse\x12I\n" +
	"\n" +
	"EndSession\x12\x1c.smartcity.EndSessionRequest\x1a\x1d.smartcity.EndSessionResponse\x12a\n" +
	"\x12ProposeUsageUpdate\x12$.smartcity.ProposeUsageUpdateRequest\x1a%.smartcity.ProposeUsageUpdateResponse\x12X\n" +
	"\x10GetChannelStatus\x12\".smartcity.GetChannelStatusRequest\x1a .smartcity.ChannelStatusResponse\x12X\n" +
	"\x0fInitiateDispute\x12!.smartcity.InitiateDisputeRequest\x1a\".smartcity.InitiateDisputeResponse\x12[\n" +
	"\x10AccumulateCredit\x12\".smartcity.AccumulateCreditRequest\x1a#.smartcity.AccumulateCreditResponse\x12[\n" +
	"\x10PostCompensation\x12\".smartcity.PostCompensationRequest\x1a#.smartcity.PostCompensationResponse\x12C\n" +
	"\bAuditLog\x12\x1a.smartcity.AuditLogRequest\x1a\x1b.smartcity.AuditLogResponse\x12B\n" +
	"\fStreamEvents\x12\x1e.smartcity.StreamEventsRequest\x1a\x10.smartcity.Event0\x01B\x1fZ\x1dsmartcity/go-perun-node/protob\x06proto3"

var (
	file_proto_smartcity_proto_rawDescOnce sync.Once
	file_proto_smartcity_proto_rawDescData []byte
)

func file_proto_smartcity_proto_rawDescGZIP() []byte {
	file_proto_smartcity_proto_rawDescOnce.Do(func() {
		file_proto_smartcity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_smartcity_proto_rawDesc), len(file_proto_smartcity_proto_rawDesc)))
	})
	return file_proto_smartcity_proto_rawDescData
}

var file_proto_smartcity_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_smartcity_proto_goTypes = []any{
	(*StartSessionRequest)(nil),        // 0: smartcity.StartSessionRequest
	(*StartSessionResponse)(nil),       // 1: smartcity.StartSessionResponse
	(*EndSessionRequest)(nil),          // 2: smartcity.EndSessionRequest
	(*EndSessionResponse)(nil),         // 3: smartcity.EndSessionResponse
	(*UsageDelta)(nil),                 // 4: smartcity.UsageDelta
	(*ProposeUsageUpdateRequest)(nil),  // 5: smartcity.ProposeUsageUpdateRequest
	(*ProposeUsageUpdateResponse)(nil), // 6: smartcity.ProposeUsageUpdateResponse
	(*GetChannelStatusRequest)(nil),    // 7: smartcity.GetChannelStatusRequest
	(*ChannelStatusResponse)(nil),      // 8: smartcity.ChannelStatusResponse
	(*InitiateDisputeRequest)(nil),     // 9: smartcity.InitiateDisputeRequest
	(*InitiateDisputeResponse)(nil),    // 10: smartcity.InitiateDisputeResponse
	(*AccumulateCreditRequest)(nil),    // 11: smartcity.AccumulateCreditRequest
	(*AccumulateCreditResponse)(nil),   // 12: smartcity.AccumulateCreditResponse
	(*PostCompensationRequest)(nil),    // 13: smartcity.PostCompensationRequest
	(*PostCompensationResponse)(nil),   // 14: smartcity.PostCompensationResponse
	(*AuditLogRequest)(nil),            // 15: smartcity.AuditLogRequest
	(*AuditLogResponse)(nil),           // 16: smartcity.AuditLogResponse
	(*StreamEventsRequest)(nil),        // 17: smartcity.StreamEventsRequest
	(*Event)(nil),                      // 18: smartcity.Event
}
var file_proto_smartcity_proto_depIdxs = []int32{
	4,  // 0: smartcity.ProposeUsageUpdateRequest.usage_delta:type_name -> smartcity.UsageDelta
	0,  // 1: smartcity.SmartCityNode.StartSession:input_type -> smartcity.StartSessionRequest
	2,  // 2: smartcity.SmartCityNode.EndSession:input_type -> smartcity.EndSessionRequest
	5,  // 3: smartcity.SmartCityNode.ProposeUsageUpdate:input_type -> smartcity.ProposeUsageUpdateRequest
	7,  // 4: smartcity.SmartCityNode.GetChannelStatus:input_type -> smartcity.GetChannelStatusRequest
	9,  // 5: smartcity.SmartCityNode.InitiateDispute:input_type -> smartcity.InitiateDisputeRequest
	11, // 6: smartcity.SmartCityNode.AccumulateCredit:input_type -> smartcity.AccumulateCreditRequest
	13, // 7: smartcity.SmartCityNode.PostCompensation:input_type -> smartcity.PostCompensationRequest
	15, // 8: smartcity.SmartCityNode.AuditLog:input_type -> smartcity.AuditLogRequest
	17, // 9: smartcity.SmartCityNode.StreamEvents:input_type -> smartcity.StreamEventsRequest
	1,  // 10: smartcity.SmartCityNode.StartSession:output_type -> smartcity.StartSessionResponse
	3,  // 11: smartcity.SmartCityNode.EndSession:output_type -> smartcity.EndSessionResponse
	6,  // 12: smartcity.SmartCityNode.ProposeUsageUpdate:output_type -> smartcity.ProposeUsageUpdateResponse
	8,  // 13: smartcity.SmartCityNode.GetChannelStatus:output_type -> smartcity.ChannelStatusResponse
	10, // 14: smartcity.SmartCityNode.InitiateDispute:output_type -> smartcity.InitiateDisputeResponse
	12, // 15: smartcity.SmartCityNode.AccumulateCredit:output_type -> smartcity.AccumulateCreditResponse
	14, // 16: smartcity.SmartCityNode.PostCompensation:output_type -> smartcity.PostCompensationResponse
	16, // 17: smartcity.SmartCityNode.AuditLog:output_type -> smartcity.AuditLogResponse
	18, // 18: smartcity.SmartCityNode.StreamEvents:output_type -> smartcity.Event
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_smartcity_proto_init() }
func file_proto_smartcity_proto_init() {
	if File_proto_smartcity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_smartcity_proto_rawDesc), len(file_proto_smartcity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_smartcity_proto_goTypes,
		DependencyIndexes: file_proto_smartcity_proto_depIdxs,
		MessageInfos:      file_proto_smartcity_proto_msgTypes,
	}.Build()
	File_proto_smartcity_proto = out.File
	file_proto_smartcity_proto_goTypes = nil
	file_proto_smartcity_proto_depIdxs = nil
}
