// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: proto/smartcity.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SmartCityNode_StartSession_FullMethodName       = "/smartcity.SmartCityNode/StartSession"
	SmartCityNode_EndSession_FullMethodName         = "/smartcity.SmartCityNode/EndSession"
	SmartCityNode_ProposeUsageUpdate_FullMethodName = "/smartcity.SmartCityNode/ProposeUsageUpdate"
	SmartCityNode_GetChannelStatus_FullMethodName   = "/smartcity.SmartCityNode/GetChannelStatus"
	SmartCityNode_InitiateDispute_FullMethodName    = "/smartcity.SmartCityNode/InitiateDispute"
	SmartCityNode_AccumulateCredit_FullMethodName   = "/smartcity.SmartCityNode/AccumulateCredit"
	SmartCityNode_PostCompensation_FullMethodName   = "/smartcity.SmartCityNode/PostCompensation"
	SmartCityNode_AuditLog_FullMethodName           = "/smartcity.SmartCityNode/AuditLog"
	SmartCityNode_StreamEvents_FullMethodName       = "/smartcity.SmartCityNode/StreamEvents"
)

// SmartCityNodeClient is the client API for SmartCityNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmartCityNodeClient interface {
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error)
	ProposeUsageUpdate(ctx context.Context, in *ProposeUsageUpdateRequest, opts ...grpc.CallOption) (*ProposeUsageUpdateResponse, error)
	GetChannelStatus(ctx context.Context, in *GetChannelStatusRequest, opts ...grpc.CallOption) (*ChannelStatusResponse, error)
	InitiateDispute(ctx context.Context, in *InitiateDisputeRequest, opts ...grpc.CallOption) (*InitiateDisputeResponse, error)
	AccumulateCredit(ctx context.Context, in *AccumulateCreditRequest, opts ...grpc.CallOption) (*AccumulateCreditResponse, error)
	PostCompensation(ctx context.Context, in *PostCompensationRequest, opts ...grpc.CallOption) (*PostCompensationResponse, error)
	AuditLog(ctx context.Context, in *AuditLogRequest, opts ...grpc.CallOption) (*AuditLogResponse, error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (SmartCityNode_StreamEventsClient, error)
}

type smartCityNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewSmartCityNodeClient(cc grpc.ClientConnInterface) SmartCityNodeClient {
	return &smartCityNodeClient{cc}
}

func (c *smartCityNodeClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, SmartCityNode_StartSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCityNodeClient) EndSession(ctx context.Context, in *EndSessionRequest, opts ...grpc.CallOption) (*EndSessionResponse, error) {
	out := new(EndSessionResponse)
	err := c.cc.Invoke(ctx, SmartCityNode_EndSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCityNodeClient) ProposeUsageUpdate(ctx context.Context, in *ProposeUsageUpdateRequest, opts ...grpc.CallOption) (*ProposeUsageUpdateResponse, error) {
	out := new(ProposeUsageUpdateResponse)
	err := c.cc.Invoke(ctx, SmartCityNode_ProposeUsageUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCityNodeClient) GetChannelStatus(ctx context.Context, in *GetChannelStatusRequest, opts ...grpc.CallOption) (*ChannelStatusResponse, error) {
	out := new(ChannelStatusResponse)
	err := c.cc.Invoke(ctx, SmartCityNode_GetChannelStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCityNodeClient) InitiateDispute(ctx context.Context, in *InitiateDisputeRequest, opts ...grpc.CallOption) (*InitiateDisputeResponse, error) {
	out := new(InitiateDisputeResponse)
	err := c.cc.Invoke(ctx, SmartCityNode_InitiateDispute_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCityNodeClient) AccumulateCredit(ctx context.Context, in *AccumulateCreditRequest, opts ...grpc.CallOption) (*AccumulateCreditResponse, error) {
	out := new(AccumulateCreditResponse)
	err := c.cc.Invoke(ctx, SmartCityNode_AccumulateCredit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCityNodeClient) PostCompensation(ctx context.Context, in *PostCompensationRequest, opts ...grpc.CallOption) (*PostCompensationResponse, error) {
	out := new(PostCompensationResponse)
	err := c.cc.Invoke(ctx, SmartCityNode_PostCompensation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCityNodeClient) AuditLog(ctx context.Context, in *AuditLogRequest, opts ...grpc.CallOption) (*AuditLogResponse, error) {
	out := new(AuditLogResponse)
	err := c.cc.Invoke(ctx, SmartCityNode_AuditLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smartCityNodeClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (SmartCityNode_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SmartCityNode_ServiceDesc.Streams[0], SmartCityNode_StreamEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &smartCityNodeStreamEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SmartCityNode_StreamEventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type smartCityNodeStreamEventsClient struct {
	grpc.ClientStream
}

func (x *smartCityNodeStreamEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SmartCityNodeServer is the server API for SmartCityNode service.
// All implementations must embed UnimplementedSmartCityNodeServer
// for forward compatibility
type SmartCityNodeServer interface {
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error)
	ProposeUsageUpdate(context.Context, *ProposeUsageUpdateRequest) (*ProposeUsageUpdateResponse, error)
	GetChannelStatus(context.Context, *GetChannelStatusRequest) (*ChannelStatusResponse, error)
	InitiateDispute(context.Context, *InitiateDisputeRequest) (*InitiateDisputeResponse, error)
	AccumulateCredit(context.Context, *AccumulateCreditRequest) (*AccumulateCreditResponse, error)
	PostCompensation(context.Context, *PostCompensationRequest) (*PostCompensationResponse, error)
	AuditLog(context.Context, *AuditLogRequest) (*AuditLogResponse, error)
	StreamEvents(*StreamEventsRequest, SmartCityNode_StreamEventsServer) error
	mustEmbedUnimplementedSmartCityNodeServer()
}

// UnimplementedSmartCityNodeServer must be embedded to have forward compatible implementations.
type UnimplementedSmartCityNodeServer struct {
}

func (UnimplementedSmartCityNodeServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedSmartCityNodeServer) EndSession(context.Context, *EndSessionRequest) (*EndSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndSession not implemented")
}
func (UnimplementedSmartCityNodeServer) ProposeUsageUpdate(context.Context, *ProposeUsageUpdateRequest) (*ProposeUsageUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeUsageUpdate not implemented")
}
func (UnimplementedSmartCityNodeServer) GetChannelStatus(context.Context, *GetChannelStatusRequest) (*ChannelStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannelStatus not implemented")
}
func (UnimplementedSmartCityNodeServer) InitiateDispute(context.Context, *InitiateDisputeRequest) (*InitiateDisputeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateDispute not implemented")
}
func (UnimplementedSmartCityNodeServer) AccumulateCredit(context.Context, *AccumulateCreditRequest) (*AccumulateCreditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccumulateCredit not implemented")
}
func (UnimplementedSmartCityNodeServer) PostCompensation(context.Context, *PostCompensationRequest) (*PostCompensationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostCompensation not implemented")
}
func (UnimplementedSmartCityNodeServer) AuditLog(context.Context, *AuditLogRequest) (*AuditLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditLog not implemented")
}
func (UnimplementedSmartCityNodeServer) StreamEvents(*StreamEventsRequest, SmartCityNode_StreamEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedSmartCityNodeServer) mustEmbedUnimplementedSmartCityNodeServer() {}

// UnsafeSmartCityNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmartCityNodeServer will
// result in compilation errors.
type UnsafeSmartCityNodeServer interface {
	mustEmbedUnimplementedSmartCityNodeServer()
}

func RegisterSmartCityNodeServer(s grpc.ServiceRegistrar, srv SmartCityNodeServer) {
	s.RegisterService(&SmartCityNode_ServiceDesc, srv)
}

func _SmartCityNode_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCityNodeServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCityNode_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCityNodeServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCityNode_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCityNodeServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCityNode_EndSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCityNodeServer).EndSession(ctx, req.(*EndSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCityNode_ProposeUsageUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeUsageUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCityNodeServer).ProposeUsageUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCityNode_ProposeUsageUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCityNodeServer).ProposeUsageUpdate(ctx, req.(*ProposeUsageUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCityNode_GetChannelStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCityNodeServer).GetChannelStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCityNode_GetChannelStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCityNodeServer).GetChannelStatus(ctx, req.(*GetChannelStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCityNode_InitiateDispute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateDisputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCityNodeServer).InitiateDispute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCityNode_InitiateDispute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCityNodeServer).InitiateDispute(ctx, req.(*InitiateDisputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCityNode_AccumulateCredit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccumulateCreditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCityNodeServer).AccumulateCredit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCityNode_AccumulateCredit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCityNodeServer).AccumulateCredit(ctx, req.(*AccumulateCreditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCityNode_PostCompensation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCompensationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCityNodeServer).PostCompensation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCityNode_PostCompensation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCityNodeServer).PostCompensation(ctx, req.(*PostCompensationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCityNode_AuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartCityNodeServer).AuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SmartCityNode_AuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartCityNodeServer).AuditLog(ctx, req.(*AuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmartCityNode_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SmartCityNodeServer).StreamEvents(m, &smartCityNodeStreamEventsServer{stream})
}

type SmartCityNode_StreamEventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type smartCityNodeStreamEventsServer struct {
	grpc.ServerStream
}

func (x *smartCityNodeStreamEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

// SmartCityNode_ServiceDesc is the grpc.ServiceDesc for SmartCityNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SmartCityNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartcity.SmartCityNode",
	HandlerType: (*SmartCityNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _SmartCityNode_StartSession_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _SmartCityNode_EndSession_Handler,
		},
		{
			MethodName: "ProposeUsageUpdate",
			Handler:    _SmartCityNode_ProposeUsageUpdate_Handler,
		},
		{
			MethodName: "GetChannelStatus",
			Handler:    _SmartCityNode_GetChannelStatus_Handler,
		},
		{
			MethodName: "InitiateDispute",
			Handler:    _SmartCityNode_InitiateDispute_Handler,
		},
		{
			MethodName: "AccumulateCredit",
			Handler:    _SmartCityNode_AccumulateCredit_Handler,
		},
		{
			MethodName: "PostCompensation",
			Handler:    _SmartCityNode_PostCompensation_Handler,
		},
		{
			MethodName: "AuditLog",
			Handler:    _SmartCityNode_AuditLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _SmartCityNode_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/smartcity.proto",
}
